### ISSUE TITLE
IllegalStateException for LENIENT_ORDER if there is more then one item from actual list in expected list

### ISSUE THREAD

**Issue by BooEnya** [arteam/unitils#1]
**Steps:**
1. Perform:
`
    public static void main(String[] args) {
        ReflectionAssert.assertReflectionEquals(Arrays.asList(1, 1), Collections.singletonList(1),
                ReflectionComparatorMode.LENIENT_ORDER);
    }
`

**Actual Results:**
`
Exception in thread "main" java.lang.IllegalStateException
	at java.util.ArrayList$Itr.remove(ArrayList.java:864)
	at org.unitils.reflectionassert.comparator.impl.LenientOrderCollectionComparator.removeMatchingIndexes(LenientOrderCollectionComparator.java:227)
	at org.unitils.reflectionassert.comparator.impl.LenientOrderCollectionComparator.fillBestMatchingIndexes(LenientOrderCollectionComparator.java:178)
	at org.unitils.reflectionassert.comparator.impl.LenientOrderCollectionComparator.compare(LenientOrderCollectionComparator.java:89)
	at org.unitils.reflectionassert.ReflectionComparator.getDifference(ReflectionComparator.java:123)
	at org.unitils.reflectionassert.ReflectionComparator.getDifference(ReflectionComparator.java:91)
	at org.unitils.reflectionassert.ReflectionAssert.assertReflectionEquals(ReflectionAssert.java:137)
	at org.unitils.reflectionassert.ReflectionAssert.assertReflectionEquals(ReflectionAssert.java:102)
`

**Expected Results:**
AssertionFailedError exception with error message about diffecrence.

**Java version:** 1.8.0_92
**Maven dependency:**
`<dependency>
	<groupId>org.unitils</groupId>
	<artifactId>unitils-core</artifactId>
	<version>3.4.3</version>
</dependency>`

**Note:** 
**it is not reproducible:**
- without LENIENT_ORDER
- if specify:
`
ReflectionAssert.assertReflectionEquals(Arrays.asList(1, 1), Arrays.asList(1, 1),
                ReflectionComparatorMode.LENIENT_ORDER);
`

**it is also reproducible:**
- if specify:
`
ReflectionAssert.assertReflectionEquals(Arrays.asList(1, 1), Arrays.asList(1, 1, 1),
                ReflectionComparatorMode.LENIENT_ORDER);
`

**Comment by arteam** [comment]
Thanks for reporting this issue, but this fork is not actively maintained, it was created only for internal purposes. Please try to reach out to the original Unitils maintainers.
